### ISSUE TITLE
edge bend does not work

### ISSUE THREAD

**Issue by bbw9n** [jluttine/tikz-bayesnet#4]
How to bend the edges? When i add the option [bend right=30], the edge is still straight.

**Comment by bodin-e** [comment]
The problem with the bend option seem to be back. E.g. [bend right=30] does not seem to work. Could there have been any changes to tikzpicture breaking this?

This is a very helpful library, cheers.

**Comment by akashrajkn** [comment]
[bend right] does not work anymore. Any suggestions?

The library is great by the way. Thank you.

**Comment by RylanSchaeffer** [comment]
Did anyone find a solution?

**Comment by mattiabr1** [comment]
https://tex.stackexchange.com/questions/423433/bent-arrows-in-tikz
